- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    metadata:
      name: "{{ argocd_namespace }}"

- name: Add Helm repo for ArgoCD
  community.kubernetes.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD via Helm
  community.kubernetes.helm:
    name: argocd
    namespace: "{{ argocd_namespace }}"
    chart: argo/argo-cd
    version: "{{ argocd_version }}"
    create_namespace: true
    wait: true
    release_namespace: "{{ argocd_namespace }}"


